[package]
name = "rufipectus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slice-dst = "1.5.1"
exact_repeat = { path = "../exact_repeat" }
rand = "0.8.5"
